spring:
  profiles: 
    active: dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-kayn-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-kayn-test